[package]
name = "eventsourcing"
version = "0.1.0"
authors = ["haraldmaida"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
